
const IDENTIFIER = '@@player/';

const FETCH_PLAYLIST_SUCCESS = `${IDENTIFIER}FETCH_PLAYLIST_SUCCESS`;
const FETCH_PLAYLIST_FAILURE = `${IDENTIFIER}FETCH_PLAYLIST_FAILURE`;
const FETCH_PLAYLIST_REQUEST = `${IDENTIFIER}FETCH_PLAYLIST_REQUEST`;

const AUTH_SUCCESS = `${IDENTIFIER}AUTH_SUCCESS`;
const AUTH_FAILURE = `${IDENTIFIER}AUTH_FAILURE`;
const AUTH_REQUEST = `${IDENTIFIER}AUTH_REQUEST`;

export {
    FETCH_PLAYLIST_SUCCESS,
    FETCH_PLAYLIST_FAILURE,
    FETCH_PLAYLIST_REQUEST,
    AUTH_SUCCESS,
    AUTH_FAILURE,
    AUTH_REQUEST
}
