
const IDENTIFIER = '@@player/';

const FETCH_PLAYLIST_SUCCESS = `${IDENTIFIER}FETCH_PLAYLIST_SUCCESS`;
const FETCH_PLAYLIST_FAILURE = `${IDENTIFIER}FETCH_PLAYLIST_FAILURE`;
const FETCH_PLAYLIST_REQUEST = `${IDENTIFIER}FETCH_PLAYLIST_REQUEST`;
const FETCH_PLAYLIST_PREFIX= 'FETCH_PLAYLIST';

export {
    FETCH_PLAYLIST_SUCCESS,
    FETCH_PLAYLIST_FAILURE,
    FETCH_PLAYLIST_REQUEST
}
