
const IDENTIFIER = '@@player/';

const FETCH_PANELLIST_SUCCESS = `${IDENTIFIER}FETCH_PANELLIST_SUCCESS`;
const FETCH_PANELLIST_FAILURE = `${IDENTIFIER}FETCH_PANELLIST_FAILURE`;
const FETCH_PANELLIST_REQUEST = `${IDENTIFIER}FETCH_PANELLIST_REQUEST`;

const FETCH_SELECTEDITEM_SUCCESS = `${IDENTIFIER}FETCH_SELECTEDITEM_SUCCESS`;
const FETCH_SELECTEDITEM_FAILURE = `${IDENTIFIER}FETCH_SELECTEDITEM_FAILURE`;
const FETCH_SELECTEDITEM_REQUEST = `${IDENTIFIER}FETCH_SELECTEDITEM_REQUEST`;
const CLEAR_SELECTEDITEM = `${IDENTIFIER}NULL_SELECTEDITEM`;

const FETCH_SELECTEDTRACK_SETID = `${IDENTIFIER}FETCH_SELECTEDTRACK_SETID`;

export {
    FETCH_SELECTEDTRACK_SETID ,
    FETCH_SELECTEDITEM_SUCCESS,
    FETCH_SELECTEDITEM_FAILURE,
    FETCH_SELECTEDITEM_REQUEST,
    CLEAR_SELECTEDITEM,
    FETCH_PANELLIST_SUCCESS,
    FETCH_PANELLIST_FAILURE,
    FETCH_PANELLIST_REQUEST,
}
